<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260222072658 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE project (id UUID NOT NULL, name VARCHAR(255) NOT NULL, api_key VARCHAR(64) NOT NULL, allowed_domains JSON NOT NULL, webhook_url VARCHAR(2048) DEFAULT NULL, retention_days INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2FB3D0EEC912ED9D ON project (api_key)');
        $this->addSql('CREATE TABLE report (id UUID NOT NULL, group_id UUID DEFAULT NULL, status VARCHAR(20) NOT NULL, message TEXT NOT NULL, category VARCHAR(50) NOT NULL, severity VARCHAR(20) NOT NULL, reporter_email VARCHAR(255) DEFAULT NULL, user_context JSON DEFAULT NULL, custom_metadata JSON DEFAULT NULL, device_info JSON DEFAULT NULL, page_url VARCHAR(2048) DEFAULT NULL, timeline JSON DEFAULT NULL, console_errors JSON DEFAULT NULL, network_failures JSON DEFAULT NULL, consent_given BOOLEAN NOT NULL, search_vector TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id UUID NOT NULL, assigned_to_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C42F7784166D1F9C ON report (project_id)');
        $this->addSql('CREATE INDEX IDX_C42F7784F4BD7827 ON report (assigned_to_id)');
        $this->addSql('CREATE INDEX idx_report_status ON report (status)');
        $this->addSql('CREATE INDEX idx_report_created_at ON report (created_at)');
        $this->addSql('CREATE INDEX idx_report_group_id ON report (group_id)');
        $this->addSql('CREATE TABLE report_attachment (id UUID NOT NULL, filename VARCHAR(255) NOT NULL, filepath VARCHAR(512) NOT NULL, size INT NOT NULL, mime_type VARCHAR(127) NOT NULL, report_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6A1DF5804BD2A4C0 ON report_attachment (report_id)');
        $this->addSql('CREATE TABLE report_comment (id UUID NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, report_id UUID NOT NULL, author_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F4ED2F6C4BD2A4C0 ON report_comment (report_id)');
        $this->addSql('CREATE INDEX IDX_F4ED2F6CF675F31B ON report_comment (author_id)');
        $this->addSql('CREATE TABLE setting (id UUID NOT NULL, key VARCHAR(255) NOT NULL, value JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9F74B8988A90ABA9 ON setting (key)');
        $this->addSql('CREATE TABLE "user" (id UUID NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, roles JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784F4BD7827 FOREIGN KEY (assigned_to_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE report_attachment ADD CONSTRAINT FK_6A1DF5804BD2A4C0 FOREIGN KEY (report_id) REFERENCES report (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE report_comment ADD CONSTRAINT FK_F4ED2F6C4BD2A4C0 FOREIGN KEY (report_id) REFERENCES report (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE report_comment ADD CONSTRAINT FK_F4ED2F6CF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F7784166D1F9C');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F7784F4BD7827');
        $this->addSql('ALTER TABLE report_attachment DROP CONSTRAINT FK_6A1DF5804BD2A4C0');
        $this->addSql('ALTER TABLE report_comment DROP CONSTRAINT FK_F4ED2F6C4BD2A4C0');
        $this->addSql('ALTER TABLE report_comment DROP CONSTRAINT FK_F4ED2F6CF675F31B');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE report');
        $this->addSql('DROP TABLE report_attachment');
        $this->addSql('DROP TABLE report_comment');
        $this->addSql('DROP TABLE setting');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
